# Unit 1 Captstone: Matching GMO Corn Crops to Yields from 2000-18

### **About my dataset**

I am using the USDA Study of Adoption for Genetically Engineered Crops in the U.S. output dataset from 2000-18 from USDA ERS Department of Agriculture Economic Research Service, this dataset only features the percentage of GMO seed used in the Corn, Soybean and Upland Cotton industry during this timeline and can be found __[here](https://www.ers.usda.gov/data-products/adoption-of-genetically-engineered-crops-in-the-us/)__  . The second dataset we are using comes from the UN FAO (Food and Agriculture Organization of United Nations) which has the acre production, yields, and harvest for corn nationwide for the USA. There is a link __[here](http://www.fao.org/faostat/en/#data/QC)__ as a reference.

In [5]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

fao_stat_dataset = pd.read_csv('FAOSTAT_data_1-31-2019.csv')
gecrops_dataset = pd.read_csv('GEcrops.csv')

In [4]:
fao_stat_dataset.head()

,Domain Code,Domain,Area Code,Area,Element Code,Element,Item Code,Item,Year Code,Year,Unit,Value,Flag,Flag Description
0,QC,Crops,231,United States of America,5312,Area harvested,56,Maize,2000,2000,ha,29315740,NaN,Official data
1,QC,Crops,231,United States of America,5312,Area harvested,56,Maize,2001,2001,ha,27829720,NaN,Official data
2,QC,Crops,231,United States of America,5312,Area harvested,56,Maize,2002,2002,ha,28057160,NaN,Official data
3,QC,Crops,231,United States of America,5312,Area harvested,56,Maize,2003,2003,ha,28710330,NaN,Official data
4,QC,Crops,231,United States of America,5312,Area harvested,56,Maize,2004,2004,ha,29797730,NaN,Official data

In [6]:
gecrops_dataset.head()

,State,Crop,Crop title,Variety,Year,Unit,Value
0,Illinois,Corn,Genetically engineered (GE) corn varieties,Insect-resistant (Bt) only ...,2000,Percent of all corn planted,13
1,Illinois,Corn,Genetically engineered (GE) corn varieties,Insect-resistant (Bt) only ...,2001,Percent of all corn planted,12
2,Illinois,Corn,Genetically engineered (GE) corn varieties,Insect-resistant (Bt) only ...,2002,Percent of all corn planted,18
3,Illinois,Corn,Genetically engineered (GE) corn varieties,Insect-resistant (Bt) only ...,2003,Percent of all corn planted,23
4,Illinois,Corn,Genetically engineered (GE) corn varieties,Insect-resistant (Bt) only ...,2004,Percent of all corn planted,26